server:
  port: 8088

spring:
  datasource:   # 数据源的相关配置
    url: jdbc:mysql://120.27.3.114:3306/foodie_shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
############################################################
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
